### ISSUE TITLE
DM 커맨드 Embed 안됨...

### ISSUE THREAD

**Issue by junhg0211** [Shtelo/MinicIII#15]
![image](https://user-images.githubusercontent.com/29883701/69947910-02569c00-1532-11ea-891b-9fe28bb8ec34.png)
DM에서는 길드 아이콘을 썸네일로 가지는 `Embed`를 추가할 수 없습니다. 고쳐주세요!!

**Comment by zer0ken** [comment]
What about just using the profile pic of itself(Minic)?

**Comment by junhg0211** [comment]
Oh I repaired this but didn't close this issue
