### ISSUE TITLE
가입 신청 - 투표 메시지에서 트위터 아이디를 마크다운으로 인식함

### ISSUE THREAD

**Issue by zer0ken** [Shtelo/MinicIII#2]
![image](https://user-images.githubusercontent.com/31297454/69910637-0b703c00-1452-11ea-8a9f-2a390e6b0bb2.png)

트위터 아이디에 언더바가 두 개 이상 들어갈 경우, 디스코드 마크다운으로 인식되어 텍스트가 편집됩니다.

**Comment by junhg0211** [comment]
> ![image](https://user-images.githubusercontent.com/31297454/69910637-0b703c00-1452-11ea-8a9f-2a390e6b0bb2.png)
> 
> 트위터 아이디에 언더바가 두 개 이상 들어갈 경우, 디스코드 마크다운으로 인식되어 텍스트가 편집됩니다.
