### ISSUE TITLE
Embed 메시지의 가독성 개선

### ISSUE THREAD

**Issue by zer0ken** [Shtelo/MinicIII#4]
`Discord.Embed`의 각 `field` 속성 중 `inline`을 `true`로 설정하면 필드가 가로로 나열되지 않도록 할 수 있습니다! 얼마 전에 Embed의 표시 방식이 변경되어, Embed를 사용하는 그 밖의 명령어나 기능들도 수정이 필요할 지 모릅니다!

**Comment by junhg0211** [comment]
지금 알아보니 `inline`을 `False`로 해야하는 것이었군요.
![image](https://user-images.githubusercontent.com/29883701/70598698-c1940c80-1c2e-11ea-91df-f8ddf3e2ae01.png)
위 사진이 모든 `field`의 `inline`을 `False`로 한 `Embed`입니다. 확실히 가독성이 더 좋군요.
