### ISSUE TITLE
어떤 명령어가 있는지 확인하는 명령어 필요

### ISSUE THREAD

**Issue by zer0ken** [Shtelo/MinicIII#5]
무슨 명령어가 있는지 알 방법이 없어요. 그냥.... 없어요!

**Comment by junhg0211** [comment]
[슈텔로 홈페이지](http://shtelo.iptime.org/)에서 확인은 해 볼 수 있습니다. 어떤 방식으로 하면 좋을까요??

**Comment by zer0ken** [comment]
예를 들자면, `$명령어`에 대해 다음과 같이 응답해준다면 편할 것 같습니다.

> $데크 - 이 명령어는 1982년 런던에서...
$데크관리 - 진사오미신유술해
...
구체적인 설명은 `$도움말 <명령어>`로 확인해라 이말이다-!

**Comment by junhg0211** [comment]
**할 일**

* [ ] 기능 구현
* [ ] 홈페이지 추가
* [ ] 문서 추가
